import type { NextPage } from "next";
import Head from "next/head";

import { useAuth, UserButton } from "@clerk/nextjs";
import Link from "next/link";

const PostCard: React.FC = () => {
  return (
    <div className="max-w-2xl rounded-lg border-2 border-gray-500 p-4 transition-all hover:scale-[101%]">
      <h2 className="text-2xl font-bold text-[hsl(280,100%,70%)]">
        {/* {post.title} */}
      </h2>
      {/* <p>{post.content}</p> */}
    </div>
  );
};

const Home: NextPage = () => {
  const { isSignedIn, isLoaded } = useAuth();

  return (
    <>
      <Head>
        <title>Lucidlock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-8">
        <h1 className="text-3xl font-extrabold">Landing Page</h1>
        <Link href="/app">
          <span className="btn">App</span>
        </Link>
      </div>
    </>
  );
};

export default Home;
